name: tollswift_bd
description: Cashless Toll Revolution in Bangladesh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

  # State & Navigation
  flutter_riverpod: ^2.5.1
  go_router: ^14.3.0

  # UI
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  

  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  fpdart: ^1.1.0

  mobile_scanner: ^5.2.1
  vibration: ^2.0.0
  http: ^1.2.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  google_ml_kit: ^0.17.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.8.0


  # ADD THESE 3 LINES â€” SOLVES YOUR ERROR
  

dependency_overrides:
  analyzer: ^9.0.0

#flutter:
#  uses-material-design: true
#  generate: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/images/
    - lib/assets/lottie/
#
#  fonts:
#    - family: ProductSans
#      fonts:
#        - asset: assets/fonts/ProductSans-Regular.ttf
#        - asset: assets/fonts/ProductSans-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/ProductSans-Bold.ttf
#          weight: 700